Use sha

diff --git a/.github/workflows/update-from-terminusdb.yml b/.github/workflows/update-from-terminusdb.yml
--- a/.github/workflows/update-from-terminusdb.yml
+++ b/.github/workflows/update-from-terminusdb.yml
@@ -1,7 +1,6 @@
 name: Update files from terminusdb
 
 on:
-  workflow_dispatch:
   repository_dispatch:
     types:
       - update-from-terminusdb
@@ -17,13 +16,11 @@ jobs:
         with:
           path: terminusdb-docs
 
-      - name: Set terminusdb_ref
-        id: set
+      - name: Check client_payload
         run: |
-          if [[ "${{ github.event.client_payload.commit }}" ]]; then
-            echo "::set-output name=terminusdb_ref::${{ github.event.client_payload.commit }}"
-          else
-            echo "::set-output name=terminusdb_ref::main"
+          if [ "${{ github.event.client_payload.sha }}" == "" ]]; then
+            echo "Missing: github.event.client_payload.sha"
+            exit 1
           fi
 
       - name: Check out terminusdb
@@ -31,7 +28,7 @@ jobs:
         with:
           path: terminusdb
           repository: terminusdb/terminusdb
-          ref: ${{ steps.set.outputs.terminusdb_ref }}
+          ref: ${{ github.event.client_payload.sha }}
 
       - name: Updates cli.md
         run: cp terminusdb/docs/terminusdb.1.ronn terminusdb-docs/readme/terminusx-db/reference-guides/cli.md
@@ -51,4 +48,4 @@ jobs:
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           repository: terminusdb-docs
-          commit_message: Update files from terminusdb
+          commit_message: Update from terminusdb@${{ github.event.client_payload.sha }}
